### PR TITLE
Release 1.0

### PR DESCRIPTION
**Pull request by jspengeman**
This is our first major release gentlemen, I would like everyone to get familar with the project in its current state. This means go ahead and go through it and test that all the functionality is there, in conjunction with that act as quality assurance testers as well, if you see a bug create a ticket on trello, notify the team and fix it. Good coding gents. Here is another joke: 

What did Lil Jon do when the hardware store employee tried to sell him a lightbulb? 
Turned down 4 Watt.

### CODE REVIEW

**Comment by JustinWatt** [comment]
Boo that joke.

**Comment by jspengeman** [comment]
I couldn't find anything MORE cheesy then that lol

Chat with me on skype when you get a sec.

**Comment by JustinWatt** [comment]
Is this good to go?

**Comment by jspengeman** [comment]
I'd say so good sir, although as the pull request states I'd like everyone to go work with it but if you have checked out develop at its current state and it works feel free to go ahead and merge the pull request.

**Comment by jspengeman** [comment]
BOOM!

**Pull request merged**
